{{/*
#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "platform-job.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-job.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "platform-job.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "platform-job.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "platform-job.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: database-alive-check
          securityContext:
            {{- toYaml .Values.database.securityContext | nindent 12 }}
          image: "{{ .Values.database.initContainerImage.repository }}:{{ .Values.database.initContainerImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.database.initContainerImage.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              {{- .Values.database.databaseCheck | nindent 14 }}
          env:
            {{- range $define := .Values.global -}}
            {{-   range $config, $value := $define.config }}
            {{-     if or (eq $define.name "pf-global") (eq $define.name "pf-database") }}
            - name: {{ $config }}
              valueFrom:
                configMapKeyRef:
                  name: platform-params-{{ $define.name }}
                  key: {{ $config }}
            {{-     end -}}
            {{-   end -}}
            {{-   range $secret, $value := $define.secret }}
            {{-     if or (eq $define.name "pf-database") }}
            - name: {{ $secret }}
              valueFrom:
                secretKeyRef:
                  name: platform-secret-{{ $define.name }}
                  key: {{ $secret }}
            {{-     end }}
            {{-   end }}
            {{- end }}
      containers:
        - name: {{ template "platform-job.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "platform-job.repository" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $define := .Values.global -}}
            {{-   range $config, $value := $define.config -}}
            {{-     if or (eq $define.name "pf-global") (eq $define.name "pf-ita") (eq $define.name "keycloak") (eq $define.name "pf-database") (and (eq $define.name "proxy-global") $define.enabled) }}
            - name: {{ $config }}
              valueFrom:
                configMapKeyRef:
                  name: platform-params-{{ $define.name }}
                  key: {{ $config }}
            {{-     end -}}
            {{-   end -}}
            {{-   range $secret, $value := $define.secret -}}
            {{-     if or (eq $define.name "pf-global") (eq $define.name "pf-database")}}
            - name: {{ $secret }}
              valueFrom:
                secretKeyRef:
                  name: platform-secret-{{ $define.name }}
                  key: {{ $secret }}
            {{-     end }}
            {{-   end }}
            {{- end -}}
            {{ range $config, $value := .Values.extraEnv }}
            - name: {{ $config }}
              valueFrom:
                configMapKeyRef:
                  name: params-{{ template "platform-job.name" $ }}
                  key: {{ $config }}
            {{- end }}
          volumeMounts:
            - name: volume-{{ template "platform-job.name" . }}-tmp
              mountPath: {{ .Values.persistence.mountPath.tmp }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
      volumes:
        - name: volume-{{ template "platform-job.name" . }}-tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
