apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ita-ag-oase
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/data/exastro-suite/exastro-agent/ita-ag-oase
    type: DirectoryOrCreate
