# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  itaGlobalDefinition:
    name: ita-global
    enabled: true
    image:
      registry: "docker.io"
      organization: exastro
      package: exastro-it-automation
    config:
      DEFAULT_LANGUAGE: "ja"
      LANGUAGE: "en"
      CONTAINER_BASE: "kubernetes"
      TZ: "Asia/Tokyo"
      STORAGEPATH: "/storage/"
    secret:
      ENCRYPT_KEY: ""
    persistence:
      enabled: true
      reinstall: false
      accessMode: ReadWriteMany
      size: 10Gi
      volumeType: hostPath # e.g.) hostPath or AKS
      storageClass: "-" # e.g.) azurefile or - (None)
      # matchLabels: 
      #   release: "stable"
      # matchExpressions:
      #   - {key: environment, operator: In, values: [dev]}
  itaDatabaseDefinition:
    name: ita-database
    enabled: true
    config:
      DB_VENDOR: "mariadb"
      DB_HOST: "mariadb"
      DB_PORT: "3306"
      DB_DATABASE: "ITA_DB"
    secret:
      DB_ADMIN_USER: "root"
      DB_ADMIN_PASSWORD: "Ch@ngeMeDBAdm"
      DB_USER: "ITA_USER"
      DB_PASSWORD: "Ch@ngeMeITADB"
  gitlabDefinition:
    name: gitlab
    enabled: true
    config:
      GITLAB_PROTOCOL: "http" 
      GITLAB_HOST: "gitlab"
      GITLAB_PORT: "8080"
    secret:
      GITLAB_ROOT_PASSWORD: "Ch@ngeMeGL"
      GITLAB_ROOT_TOKEN: "change-this-token"
  mongoDefinition:
    name: mongo
    enabled: true
    config:
      MONGO_PROTOCOL: "http"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
    secret:
      MONGO_ADMIN_USERNAME: "admin"
      MONGO_ADMIN_PASSWORD: "Ch@ngeMeMGAdm"